# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## Section 1.


 I selected **Lane 2 – Refresh / Content Opportunity Scoring**.

I chose this lane because it focuses on identifying which content pages should be reviewed first based on search performance and engagement signals. This helps content teams prioritize their work efficiently and make data-driven decisions. Since the starter dataset contains content performance metrics, it provides a good foundation for exploring this problem over the next seven weeks.

## Section 2.


**Decision**

Which content pages should be reviewed first for refresh or improvement?

**Who takes the action?**

SEO specialists, content managers, or website administrators.

**Action**

Review and update the highest-priority pages based on the ranking produced by the analysis.

**Cost of a wrong recommendation**

If the wrong pages are prioritized, valuable time and resources may be spent on pages with little impact, while high-value opportunities remain unnoticed.

**Why machine learning?**

Machine learning can analyze multiple performance signals together and identify patterns that are difficult to capture using simple rule-based methods.

## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

In [12]:
from google.colab import files
import os

print("Please upload the 'content_refresh_anonymized.csv' file:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Please upload the 'content_refresh_anonymized.csv' file:

Saving content_refresh_anonymized.csv to content_refresh_anonymized.csv
User uploaded file "content_refresh_anonymized.csv" with length 6727670 bytes

In [13]:
# Create the directory structure if it doesn't exist
output_dir = 'data/raw'
os.makedirs(output_dir, exist_ok=True)

# Determine the actual filename on disk after upload.
# Colab's `files.upload()` can sometimes save with the original name even if `uploaded.keys()`
# indicates a renamed version (e.g., adding `(1)`). We look for the base name
# 'content_refresh_anonymized.csv' in the current directory.
actual_source_filename = None
for filename in os.listdir('.'):
    if filename.startswith('content_refresh_anonymized.csv'):
        actual_source_filename = filename
        break

if actual_source_filename:
    destination_path = os.path.join(output_dir, 'content_refresh_anonymized.csv')
    os.rename(actual_source_filename, destination_path)
    print(f"Moved '{actual_source_filename}' to '{destination_path}'")
elif uploaded.keys():
    # Fallback: if the exact base name wasn't found by os.listdir, try the key from uploaded.
    # This handles cases where `uploaded.keys()` might be more accurate or the file name has changed.
    uploaded_key = list(uploaded.keys())[0]
    if os.path.exists(uploaded_key):
        destination_path = os.path.join(output_dir, 'content_refresh_anonymized.csv')
        os.rename(uploaded_key, destination_path)
        print(f"Moved '{uploaded_key}' to '{destination_path}' (using uploaded key as source)")
    else:
        print(f"Error: Neither 'content_refresh_anonymized.csv' nor '{uploaded_key}' found in the current directory.")
        print("Please ensure the file was uploaded correctly.")
else:
    print(f"Error: Could not find 'content_refresh_anonymized.csv' or a similarly named file "
          "in the current directory. Please ensure the file was uploaded correctly.")

Moved 'content_refresh_anonymized.csv' to 'data/raw/content_refresh_anonymized.csv'

In [14]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [15]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.describe()

Rows: 30000
Columns: 44

,search_volume,competition,cpc,word_count,char_count,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,...,sessions_prev_30d,content_age_days,age_tier_order,days_since_last_update,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,trend_pct
count,27532.000000,27532.000000,27532.000000,22301.000000,22301.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.00000,30000.000000,30000.000000,30000.000000,30000.00000,30000.000000,29875.000000,30000.000000,26612.000000
mean,158.882391,0.146954,0.485342,3107.760325,20665.277835,5200.366300,16.097333,49.942467,37.066633,35.937700,...,10.283000,256.16780,4.786533,46.098300,0.510733,16.34238,2.534520,18.212921,0.768196,-4.785969
std,1518.270825,0.285241,2.101560,1452.382598,10115.344042,16838.019547,75.076958,152.101430,107.069131,103.748185,...,42.578003,132.70793,0.790392,42.078709,3.279162,15.21679,8.310096,29.472768,7.429454,473.861780
min,0.000000,0.000000,0.000000,8.000000,40.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,90.00000,3.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,-100.000000
25%,0.000000,0.000000,0.000000,2413.000000,15644.000000,81.000000,0.000000,2.000000,2.000000,2.000000,...,1.000000,132.00000,4.000000,20.000000,0.000000,6.20000,0.000000,0.000000,0.000000,-62.600000
50%,10.000000,0.000000,0.000000,2877.000000,19116.000000,731.000000,1.000000,8.000000,7.000000,7.000000,...,2.000000,236.00000,5.000000,20.000000,0.070000,10.80000,0.000000,5.000000,0.000000,-33.500000
75%,20.000000,0.130000,0.000000,3666.000000,24011.000000,3615.250000,7.000000,33.000000,27.000000,27.000000,...,7.000000,333.00000,5.000000,104.000000,0.290000,22.30000,1.350000,23.530000,0.000000,0.000000
max,74000.000000,1.000000,100.360000,9546.000000,111158.000000,517715.000000,4178.000000,5998.000000,4345.000000,4913.000000,...,4247.000000,564.00000,6.000000,373.000000,100.000000,245.00000,100.000000,300.000000,300.000000,44900.000000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

In [17]:
df["trend_direction"].value_counts()

trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

#Section 03

The starter dataset contains **30000 rows** and **44 columns**.

The data includes search performance metrics such as impressions, clicks, sessions, CTR, average position, and content age.

The distribution of the `trend_direction` column shows how many pages are improving, stable, or declining, supporting the use of this dataset for identifying content review opportunities.

In [18]:
# Quick Look at the Data

#Section 04

# Careful Words

This project does not prove that updating a page will improve its search performance.

The analysis identifies pages that appear to be good candidates for review based on historical data.

The findings should support human decision-making rather than replace it.


#Section 05

# Self Check

✅ Selected a project lane.

✅ Defined the research question.

✅ Explained the decision and action.

✅ Included statistics from the starter dataset.

✅ Explained why machine learning is appropriate.

✅ Used careful language about the limitations.